services:
  postgres:
    image: postgres:16
    container_name: transactions-kotlin-db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: transactions-kotlin-db

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d transactions-kotlin-db"]
      interval: 5s
      timeout: 5s
      retries: 5